server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: postgres
    password: root

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    show-sql: true
validator:
  company:
    page:
      min: 10
      max: 20
code:
  currency:
    eur: 978
    jpy: 392
    gbp: 826
  status:
    sentForProcessing: 100
    waitingForTheStartOfProduction: 200
    inTheProcessOfManufacturing: 300
    waitingForDepartureToTheBranch: 400
    onDepartment: 500
    transferredToTheClient: 600


