server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: postgres
    password: root

  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
validator:
  company:
    page:
      min: 10
      max: 20
