server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    show-sql: true
validator:
  company:
    page:
      min: 10
      max: 20
code:
  currency:
     properties:
      978: Евро
      392: Японская йена
      826: Фунт стерлингов Великобритании
      def: Неизвестная валюта
  status:
     properties:
      100: Отправлена на обработку
      200: Ожидание начала изготовления
      300: В процессе изготовления
      400: Ожидает отправку в отделение
      500: В отделении
      600: Передана клиенту
      def: Состояние неизвестно
jwt:
  token:
    secret: secret
    accessExpired: 30m
    refreshExpired: 3d
cache:
  timeToLive: 10m
  maxSize: 10000
  enabled: true



